[package]
name = "cowssss"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]  # n√©cessaire pour WASM

[dependencies]
wasm-bindgen = "0.2"  # pour interop JS
web-sys = { version = "0.3.82", features = ["CanvasRenderingContext2d"] }
